---
# Compute Optimized Node Pool
# For CPU-intensive workloads (data processing, batch jobs, analytics)

apiVersion: eks.amazonaws.com/v1
kind: NodePool
metadata:
  name: compute-optimized
  labels:
    managed-by: argocd
    node-pool-type: compute
spec:
  # Compute-optimized instance types
  instanceTypes:
    - c6i.xlarge     # 4 vCPU, 8 GiB RAM
    - c6i.2xlarge    # 8 vCPU, 16 GiB RAM
    - c6i.4xlarge    # 16 vCPU, 32 GiB RAM
  
  capacityType: ON_DEMAND
  
  # Node labels for workload targeting
  labels:
    workload-type: compute-intensive
    node-pool: compute-optimized
  
  # Taint to ensure only designated workloads run here
  taints:
    - key: workload-type
      value: compute-intensive
      effect: NoSchedule
  
  # Scaling configuration
  scaling:
    minSize: 0      # Scale to zero when not needed
    maxSize: 20
    desiredSize: 2
  
  diskSize: 100
  
  tags:
    Environment: shared
    ManagedBy: ArgoCD
    CostCenter: analytics
    NodePool: compute-optimized
  
  amiFamily: AL2
