# yamllint configuration file
---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .github/
  charts/workload/templates/
