---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cldev02-quota
  namespace: cldev02
  labels:
    managed-by: argocd
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    requests.storage: 50Gi
    persistentvolumeclaims: "5"
    pods: "30"
    services: "10"
    configmaps: "30"
    secrets: "30"
    services.loadbalancers: "1"
    count/ingresses.networking.k8s.io: "5"
